### ISSUE TITLE
about reconfiguring a project

### ISSUE THREAD

**Issue by rherilier** [mohkale/projection#14]
hello,

What about adding a new action to trigger the project's reconfiguration?

Such an action is something needed to recreate a sane build configuration. For example, while doing a `git rebase` to check that the merge conflicts have been done correctly.

afaik, CMake has the option `--fresh` to do so while meson has `setup --wipe`.

my 2¢

**Comment by mohkale** [comment]
Another day. Another not-well advertised CMake option I've never heard of before XD.

Is there any reason you wouldn't always want to pass this to CMake. 

For context I think re-configuring shouldn't be seen as an option alien to just configuring. When I want to reconfigure I just rerun the configure command because that's what I'd expect to happen. I have seen CMake persisting cache stuff weirdly some times leading me to clear the build directory and run CMake from scratch. I'm of the mindset that if this makes a subsequent configure on an existing build directory actually behave like re-configuring from scratch then we should enable it by default instead of add a separate "reconfigure" option :thinking:.

**Comment by rherilier** [comment]
I found `--fresh` because I looked at the manpage while writing my previous message ;)

> Is there any reason you wouldn't always want to pass this to CMake.

I could not agree more...

> For context I think re-configuring shouldn't be seen as an option alien to just configure...

My bad, i wrote "action" while it should have been "command" to be correct.

**Comment by mohkale** [comment]
Added to default set of configure options and tested. I don't have a meson project handy to test so gonna defer that for when someone requests it :-). Thanks.

**Comment by rherilier** [comment]
You're welcome.

But I'll keep the semantic distinction in my emacs config because configure aims, for me, to set the build parameter when reconfigure is just a cleanup and a call to configure with all of the previously set parameters.

**Comment by mohkale** [comment]
That's fair, although the way projection is written these should be equivalent. We always supply all the options whether we're configuring the first time or there's already a build directory and someone happens to try to configure again. If you change configure flags for example CMake should reconfigure from scratch and if you haven't then I don't think configuring should be done at all. Forcing a blank state for reconfigure should make things easier to reason about or at the very least avoid confusion because you've reconfigured but CMake has decided some stuff from the previous configure call is still valid :upside_down_face:.
